@{
    SchemaVersion = 1
    CatalinaHome = 'C:\PATH\TO\apache-tomcat-10.1'
    StateRoot = 'C:\Users\<USER>\AppData\Local\AgriTrace\local-3node'
    Nodes = @(
        @{ Id='A'; Role='FARMER'; AppPort=8443; P2pPort=9443; DatabasePort=3307; ShutdownPort=8005; PeerId='peer-node-a-farmer'; OrganizationId='org-farmer-a'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-a'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-peer.p12'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\peer-ca-trust.p12'; P2pClientTrustStorePassword='SET_OUTSIDE_REPOSITORY'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\server-ca-trust.p12'; JavaPeerTrustStorePassword='SET_OUTSIDE_REPOSITORY' }
        @{ Id='B'; Role='CARRIER'; AppPort=8444; P2pPort=9444; DatabasePort=3308; ShutdownPort=8006; PeerId='peer-node-b-carrier'; OrganizationId='org-carrier-b'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-b'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-peer.p12'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\peer-ca-trust.p12'; P2pClientTrustStorePassword='SET_OUTSIDE_REPOSITORY'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\server-ca-trust.p12'; JavaPeerTrustStorePassword='SET_OUTSIDE_REPOSITORY' }
        @{ Id='C'; Role='RETAILER'; AppPort=8445; P2pPort=9445; DatabasePort=3309; ShutdownPort=8007; PeerId='peer-node-c-retailer'; OrganizationId='org-retailer-c'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-c'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-peer.p12'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\peer-ca-trust.p12'; P2pClientTrustStorePassword='SET_OUTSIDE_REPOSITORY'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\server-ca-trust.p12'; JavaPeerTrustStorePassword='SET_OUTSIDE_REPOSITORY' }
    )
}