@{
    SchemaVersion = 1
    CatalinaHome = 'C:\PATH\TO\apache-tomcat-10.1'
    StateRoot = 'C:\Users\<USER>\AppData\Local\AgriTrace\local-3node'
    Nodes = @(
        @{ Id='A'; Role='FARMER'; PublicBaseUrl='https://localhost:8443/AgriTrace'; AppPort=8443; P2pPort=9443; DatabasePort=3307; ShutdownPort=8005; PeerId='peer-node-a-farmer'; OrganizationId='org-farmer-a'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-a'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-peer.p12'; P2pKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-peer-password.txt'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-a-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-a-peer-trust.p12'; P2pClientTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-peer-trust-password.txt'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-a-server-trust.p12'; JavaPeerTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-a-server-trust-password.txt' }
        @{ Id='B'; Role='CARRIER'; PublicBaseUrl='https://localhost:8444/AgriTrace'; AppPort=8444; P2pPort=9444; DatabasePort=3308; ShutdownPort=8006; PeerId='peer-node-b-carrier'; OrganizationId='org-carrier-b'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-b'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-peer.p12'; P2pKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-peer-password.txt'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-b-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-b-peer-trust.p12'; P2pClientTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-peer-trust-password.txt'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-b-server-trust.p12'; JavaPeerTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-b-server-trust-password.txt' }
        @{ Id='C'; Role='RETAILER'; PublicBaseUrl='https://localhost:8445/AgriTrace'; AppPort=8445; P2pPort=9445; DatabasePort=3309; ShutdownPort=8007; PeerId='peer-node-c-retailer'; OrganizationId='org-retailer-c'; CatalinaBase='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\tomcat\node-c'; P2pKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-peer.p12'; P2pKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-peer-password.txt'; AppServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-server.p12'; AppServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-server-password.txt'; P2pServerKeyStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\identity\node-c-server.p12'; P2pServerKeyStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-server-password.txt'; P2pClientTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-c-peer-trust.p12'; P2pClientTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-peer-trust-password.txt'; JavaPeerTrustStorePath='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\trust\node-c-server-trust.p12'; JavaPeerTrustStorePasswordFile='C:\Users\<USER>\AppData\Local\AgriTrace\local-3node\secrets\node-c-server-trust-password.txt' }
    )
}
